### ISSUE TITLE
kafka join example: Invalid topology: Topic user-clicks3 has already been registered by another source.

### ISSUE THREAD

**Issue by todaynowork** [spring-cloud/spring-cloud-stream-samples#102]
https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-table-join

when execute command below, always get  Invalid topology: Topic user-clicks3 has already been registered by another source.

java -jar target/kafka-streams-table-join-0.0.1-SNAPSHOT.jar

Log detail:
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=54172:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/tools.jar:/Users/todaynowork/temp/spring-cloud-stream-samples/kafka-streams-samples/kafka-streams-table-join/target/classes:/Users/todaynowork/.m2/repository/org/springframework/cloud/spring-cloud-stream-binder-kafka-streams/2.1.0.BUILD-SNAPSHOT/spring-cloud-stream-binder-kafka-streams-2.1.0.BUILD-20181130.160426-207.jar:/Users/todaynowork/.m2/repository/org/springframework/cloud/spring-cloud-stream-binder-kafka-core/2.1.0.BUILD-SNAPSHOT/spring-cloud-stream-binder-kafka-core-2.1.0.BUILD-20181130.155806-253.jar:/Users/todaynowork/.m2/repository/org/springframework/cloud/spring-cloud-stream/2.1.0.BUILD-SNAPSHOT/spring-cloud-stream-2.1.0.BUILD-20181130.154428-236.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.1.0.BUILD-SNAPSHOT/spring-boot-starter-validation-2.1.0.BUILD-20181030.064050-619.jar:/Users/todaynowork/.m2/repository/org/springframework/integration/spring-integration-core/5.1.0.RELEASE/spring-integration-core-5.1.0.RELEASE.jar:/Users/todaynowork/.m2/repository/io/projectreactor/reactor-core/3.2.2.RELEASE/reactor-core-3.2.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/Users/todaynowork/.m2/repository/org/springframework/integration/spring-integration-jmx/5.1.0.RELEASE/spring-integration-jmx-5.1.0.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-tuple/1.0.0.RELEASE/spring-tuple-1.0.0.RELEASE.jar:/Users/todaynowork/.m2/repository/com/esotericsoftware/kryo-shaded/3.0.3/kryo-shaded-3.0.3.jar:/Users/todaynowork/.m2/repository/com/esotericsoftware/minlog/1.3.0/minlog-1.3.0.jar:/Users/todaynowork/.m2/repository/org/springframework/integration/spring-integration-tuple/1.0.0.RELEASE/spring-integration-tuple-1.0.0.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/cloud/spring-cloud-function-context/2.0.0.RC2/spring-cloud-function-context-2.0.0.RC2.jar:/Users/todaynowork/.m2/repository/org/springframework/cloud/spring-cloud-function-core/2.0.0.RC2/spring-cloud-function-core-2.0.0.RC2.jar:/Users/todaynowork/.m2/repository/org/springframework/integration/spring-integration-kafka/3.1.0.RELEASE/spring-integration-kafka-3.1.0.RELEASE.jar:/Users/todaynowork/.m2/repository/org/apache/kafka/kafka-streams/2.0.0/kafka-streams-2.0.0.jar:/Users/todaynowork/.m2/repository/org/apache/kafka/kafka-clients/2.0.0/kafka-clients-2.0.0.jar:/Users/todaynowork/.m2/repository/org/lz4/lz4-java/1.4.1/lz4-java-1.4.1.jar:/Users/todaynowork/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.1/snappy-java-1.1.7.1.jar:/Users/todaynowork/.m2/repository/org/apache/kafka/connect-json/2.0.0/connect-json-2.0.0.jar:/Users/todaynowork/.m2/repository/org/apache/kafka/connect-api/2.0.0/connect-api-2.0.0.jar:/Users/todaynowork/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar:/Users/todaynowork/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/todaynowork/.m2/repository/org/rocksdb/rocksdbjni/5.7.3/rocksdbjni-5.7.3.jar:/Users/todaynowork/.m2/repository/org/springframework/kafka/spring-kafka/2.2.0.RELEASE/spring-kafka-2.2.0.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-context/5.1.2.RELEASE/spring-context-5.1.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-messaging/5.1.2.RELEASE/spring-messaging-5.1.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-tx/5.1.2.RELEASE/spring-tx-5.1.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/retry/spring-retry/1.2.2.RELEASE/spring-retry-1.2.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-core/5.1.2.RELEASE/spring-core-5.1.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-jcl/5.1.2.RELEASE/spring-jcl-5.1.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.1.0.BUILD-SNAPSHOT/spring-boot-starter-actuator-2.1.0.BUILD-20181030.064026-620.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.1.0.BUILD-SNAPSHOT/spring-boot-actuator-autoconfigure-2.1.0.BUILD-20181030.063957-621.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-actuator/2.1.0.BUILD-SNAPSHOT/spring-boot-actuator-2.1.0.BUILD-20181030.063958-621.jar:/Users/todaynowork/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.7/jackson-databind-2.9.7.jar:/Users/todaynowork/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/Users/todaynowork/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.7/jackson-core-2.9.7.jar:/Users/todaynowork/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.7/jackson-datatype-jsr310-2.9.7.jar:/Users/todaynowork/.m2/repository/io/micrometer/micrometer-core/1.1.0/micrometer-core-1.1.0.jar:/Users/todaynowork/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar:/Users/todaynowork/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-starter/2.1.0.BUILD-SNAPSHOT/spring-boot-starter-2.1.0.BUILD-20181030.064053-619.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot/2.1.0.BUILD-SNAPSHOT/spring-boot-2.1.0.BUILD-20181030.064057-619.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.1.0.BUILD-SNAPSHOT/spring-boot-autoconfigure-2.1.0.BUILD-20181030.064003-621.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.1.0.BUILD-SNAPSHOT/spring-boot-starter-logging-2.1.0.BUILD-20181030.064044-619.jar:/Users/todaynowork/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/todaynowork/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/todaynowork/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.11.1/log4j-to-slf4j-2.11.1.jar:/Users/todaynowork/.m2/repository/org/apache/logging/log4j/log4j-api/2.11.1/log4j-api-2.11.1.jar:/Users/todaynowork/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar:/Users/todaynowork/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar:/Users/todaynowork/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.1.0.BUILD-SNAPSHOT/spring-boot-starter-web-2.1.0.BUILD-20181030.064051-619.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.1.0.BUILD-SNAPSHOT/spring-boot-starter-json-2.1.0.BUILD-20181030.064042-619.jar:/Users/todaynowork/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.7/jackson-datatype-jdk8-2.9.7.jar:/Users/todaynowork/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.7/jackson-module-parameter-names-2.9.7.jar:/Users/todaynowork/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.1.0.BUILD-SNAPSHOT/spring-boot-starter-tomcat-2.1.0.BUILD-20181030.064049-619.jar:/Users/todaynowork/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.12/tomcat-embed-core-9.0.12.jar:/Users/todaynowork/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.12/tomcat-embed-el-9.0.12.jar:/Users/todaynowork/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.12/tomcat-embed-websocket-9.0.12.jar:/Users/todaynowork/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.13.Final/hibernate-validator-6.0.13.Final.jar:/Users/todaynowork/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar:/Users/todaynowork/.m2/repository/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar:/Users/todaynowork/.m2/repository/com/fasterxml/classmate/1.4.0/classmate-1.4.0.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-web/5.1.2.RELEASE/spring-web-5.1.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-beans/5.1.2.RELEASE/spring-beans-5.1.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-webmvc/5.1.2.RELEASE/spring-webmvc-5.1.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-aop/5.1.2.RELEASE/spring-aop-5.1.2.RELEASE.jar:/Users/todaynowork/.m2/repository/org/springframework/spring-expression/5.1.2.RELEASE/spring-expression-5.1.2.RELEASE.jar kafka.streams.table.join.KafkaStreamsTableJoin

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v2.1.0.BUILD-SNAPSHOT)

2018-12-03 15:03:33,641  INFO main k.s.t.j.KafkaStreamsTableJoin:50 - Starting KafkaStreamsTableJoin on todaynoworksmbp.cn.ibm.com with PID 3345 (/Users/todaynowork/temp/spring-cloud-stream-samples/kafka-streams-samples/kafka-streams-table-join/target/classes started by todaynowork in /Users/todaynowork/temp/spring-cloud-stream-samples/kafka-streams-samples/kafka-streams-table-join)
2018-12-03 15:03:33,647  INFO main k.s.t.j.KafkaStreamsTableJoin:675 - No active profile set, falling back to default profiles: default
2018-12-03 15:03:35,261  INFO main o.s.i.c.DefaultConfiguringBeanFactoryPostProcessor:185 - No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2018-12-03 15:03:35,266  INFO main o.s.i.c.DefaultConfiguringBeanFactoryPostProcessor:271 - No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
2018-12-03 15:03:35,270  INFO main o.s.i.c.DefaultConfiguringBeanFactoryPostProcessor:421 - No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2018-12-03 15:03:35,321  INFO main o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:330 - Bean 'org.springframework.kafka.annotation.KafkaBootstrapConfiguration' of type [org.springframework.kafka.annotation.KafkaBootstrapConfiguration$$EnhancerBySpringCGLIB$$ef5c9660] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-12-03 15:03:35,370  INFO main o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:330 - Bean 'integrationDisposableAutoCreatedBeans' of type [org.springframework.integration.config.annotation.Disposables] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-12-03 15:03:35,395  INFO main o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:330 - Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration$$EnhancerBySpringCGLIB$$869c400c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-12-03 15:03:35,405  INFO main o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:330 - Bean 'org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration' of type [org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration$$EnhancerBySpringCGLIB$$622e4b2c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-12-03 15:03:35,419  INFO main o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:330 - Bean 'org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration' of type [org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration$$EnhancerBySpringCGLIB$$9b15f3f9] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-12-03 15:03:35,425  INFO main o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:330 - Bean 'mbeanServer' of type [com.sun.jmx.mbeanserver.JmxMBeanServer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-12-03 15:03:35,958  INFO main o.s.b.w.e.t.TomcatWebServer:90 - Tomcat initialized with port(s): 8080 (http)
2018-12-03 15:03:35,974  INFO main o.a.c.h.Http11NioProtocol:173 - Initializing ProtocolHandler ["http-nio-8080"]
2018-12-03 15:03:35,982  INFO main o.a.c.c.StandardService:173 - Starting service [Tomcat]
2018-12-03 15:03:35,983  INFO main o.a.c.c.StandardEngine:173 - Starting Servlet Engine: Apache Tomcat/9.0.12
2018-12-03 15:03:35,994  INFO main o.a.c.c.AprLifecycleListener:173 - The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/todaynowork/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2018-12-03 15:03:36,099  INFO main o.a.c.c.C.[.[.[/]:173 - Initializing Spring embedded WebApplicationContext
2018-12-03 15:03:36,099  INFO main o.s.w.c.ContextLoader:285 - Root WebApplicationContext: initialization completed in 2355 ms
2018-12-03 15:03:36,625  INFO main o.s.s.c.ThreadPoolTaskScheduler:171 - Initializing ExecutorService 'taskScheduler'
2018-12-03 15:03:36,847  INFO main o.s.b.w.s.FilterRegistrationBean:248 - Mapping filter: 'characterEncodingFilter' to: [/*]
2018-12-03 15:03:36,847  INFO main o.s.b.w.s.FilterRegistrationBean:248 - Mapping filter: 'webMvcMetricsFilter' to: [/*]
2018-12-03 15:03:36,847  INFO main o.s.b.w.s.FilterRegistrationBean:248 - Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-12-03 15:03:36,848  INFO main o.s.b.w.s.FilterRegistrationBean:248 - Mapping filter: 'formContentFilter' to: [/*]
2018-12-03 15:03:36,848  INFO main o.s.b.w.s.FilterRegistrationBean:248 - Mapping filter: 'requestContextFilter' to: [/*]
2018-12-03 15:03:36,848  INFO main o.s.b.w.s.FilterRegistrationBean:248 - Mapping filter: 'httpTraceFilter' to: [/*]
2018-12-03 15:03:36,848  INFO main o.s.b.w.s.ServletRegistrationBean:186 - Servlet dispatcherServlet mapped to [/]
2018-12-03 15:03:37,225  INFO main o.s.s.c.ThreadPoolTaskExecutor:171 - Initializing ExecutorService 'applicationTaskExecutor'
2018-12-03 15:03:37,774  INFO main o.s.b.a.e.w.EndpointLinksResolver:59 - Exposing 2 endpoint(s) beneath base path '/actuator'
2018-12-03 15:03:37,875  INFO main o.s.c.s.b.k.s.KafkaStreamsStreamListenerSetupMethodOrchestrator:408 - Native decoding is enabled for input. Inbound deserialization done at the broker.
2018-12-03 15:03:37,888  INFO main o.a.c.c.StandardService:173 - Stopping service [Tomcat]
2018-12-03 15:03:37,909  INFO main o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-03 15:03:37,912 ERROR main o.s.b.SpringApplication:858 - Application run failed
java.lang.IllegalStateException: org.apache.kafka.streams.errors.TopologyException: Invalid topology: Topic user-clicks3 has already been registered by another source.
	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator.adaptAndRetrieveInboundArguments(KafkaStreamsStreamListenerSetupMethodOrchestrator.java:308)
	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator.orchestrateStreamListenerSetupMethod(KafkaStreamsStreamListenerSetupMethodOrchestrator.java:164)
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.doPostProcess(StreamListenerAnnotationBeanPostProcessor.java:195)
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.lambda$postProcessAfterInitialization$0(StreamListenerAnnotationBeanPostProcessor.java:167)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.injectAndPostProcessDependencies(StreamListenerAnnotationBeanPostProcessor.java:285)
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(StreamListenerAnnotationBeanPostProcessor.java:105)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:863)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at kafka.streams.table.join.KafkaStreamsTableJoin.main(KafkaStreamsTableJoin.java:37)
Caused by: org.apache.kafka.streams.errors.TopologyException: Invalid topology: Topic user-clicks3 has already been registered by another source.
	at org.apache.kafka.streams.processor.internals.InternalTopologyBuilder.validateTopicNotAlreadyRegistered(InternalTopologyBuilder.java:569)
	at org.apache.kafka.streams.processor.internals.InternalTopologyBuilder.addSource(InternalTopologyBuilder.java:389)
	at org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder.createKTable(InternalStreamsBuilder.java:101)
	at org.apache.kafka.streams.kstream.internals.InternalStreamsBuilder.table(InternalStreamsBuilder.java:79)
	at org.apache.kafka.streams.StreamsBuilder.table(StreamsBuilder.java:279)
	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator.getKTable(KafkaStreamsStreamListenerSetupMethodOrchestrator.java:330)
	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsStreamListenerSetupMethodOrchestrator.adaptAndRetrieveInboundArguments(KafkaStreamsStreamListenerSetupMethodOrchestrator.java:287)
	... 16 common frames omitted
2018-12-03 15:03:37,919  INFO main o.s.s.c.ThreadPoolTaskExecutor:208 - Shutting down ExecutorService 'applicationTaskExecutor'
2018-12-03 15:03:37,920  INFO main o.s.s.c.ThreadPoolTaskScheduler:208 - Shutting down ExecutorService 'taskScheduler'

Process finished with exit code 1

**Comment by sobychacko** [comment]
@todaynowork Thanks for reporting this issue. Cleaned up the configuration a little bit and the sample works now. Please confirm.

**Comment by sobychacko** [comment]
Closing this issue due to inactivity.
