### ISSUE TITLE
Error when running test-embedded-kafka

### ISSUE THREAD

**Issue by gborobio73** [spring-cloud/spring-cloud-stream-samples#182]
Hello!

First of all thank you for the samples, really useful.

When I run `test-embedded-kafka` I get these errors:
```
11:20:15.233 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/var/folders/_q/_k_xnlrj6y58700m9v6wtkf00000gn/T/
11:20:15.233 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
11:20:15.233 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.name=Mac OS X
11:20:15.233 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.arch=x86_64
11:20:15.233 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.version=10.15.4
11:20:15.233 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.name=gonzalo.borobio
11:20:15.233 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.home=/Users/gonzalo.borobio
11:20:15.233 [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/Users/gonzalo.borobio/Dev/spring-cloud-stream-samples/testing-samples/test-embedded-kafka
11:20:15.235 [main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=127.0.0.1:59201 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@14c053c6
11:20:15.237 [main] DEBUG org.apache.zookeeper.ClientCnxn - zookeeper.disableAutoWatchReset is false
11:20:15.249 [main] DEBUG kafka.utils.KafkaScheduler - Initializing task scheduler.
11:20:15.250 [main] INFO kafka.zookeeper.ZooKeeperClient - [ZooKeeperClient Kafka server] Waiting until connected.
11:20:15.256 [main-SendThread(127.0.0.1:59201)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server 127.0.0.1/<unresolved>:59201, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address 127.0.0.1/<unresolved>:59201 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65)
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
11:20:16.365 [main-SendThread(127.0.0.1:59201)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server 127.0.0.1/<unresolved>:59201, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address 127.0.0.1/<unresolved>:59201 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65)
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
```

And then eventually fails with:

```
11:20:25.318 [main] ERROR kafka.server.KafkaServer - Fatal error during KafkaServer startup. Prepare to shutdown
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:258)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:254)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:112)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1826)
	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:364)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:387)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:207)
	at kafka.utils.TestUtils$.createServer(TestUtils.scala:142)
	at kafka.utils.TestUtils.createServer(TestUtils.scala)
	at org.springframework.kafka.test.EmbeddedKafkaBroker.afterPropertiesSet(EmbeddedKafkaBroker.java:305)
	at org.springframework.kafka.test.rule.EmbeddedKafkaRule.before(EmbeddedKafkaRule.java:114)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:40)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:71)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

Probably I am doing something wrong and I would really appreciate your help.

Thank you!

Gonzalo

**Comment by garyrussell** [comment]
This is a problem with Zookeeper on Java 14 (I think that's when it started); you need to use a newer zookeeper or fall back to an older JVM.

You can use the [instructions here](https://docs.spring.io/spring-kafka/docs/2.4.6.RELEASE/reference/html/#deps-for-24x) to upgrade to kafka 2.4.1 (or 2.5) which use the newer Zookeeper (3.5.7).

**Comment by gborobio73** [comment]
Hello Gary, 
Thanks a lot for your answer. I'll try to set it up with a newer zookeeper during this week and get back to you.

**Comment by gborobio73** [comment]
Hello!

Using the dependencies described [here](https://docs.spring.io/spring-kafka/docs/2.4.6.RELEASE/reference/html/#deps-for-24x) I was able to make it run.
I'll close this issue.

Thanks a lot!
