### ISSUE TITLE
Tests fail for multibinder-differentsystems

### ISSUE THREAD

**Issue by styjdt** [spring-cloud/spring-cloud-stream-samples#6]
When building spring-cloud-stream-samples the test for `multibinder-differentsystems` fail.
Error message:

    Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.641 sec <<< FAILURE! - in multibinder.TwoKafkaBindersApplicationTest
    messagingWorks(multibinder.TwoKafkaBindersApplicationTest)  Time elapsed: 0.016 sec  <<< ERROR!
    java.lang.NullPointerException: while trying to invoke the method org.springframework.cloud.stream.binder.kafka.KafkaProducerProperties.getPartitionCount() of a null object loaded from local variable 'properties'
        at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.doBindProducer(KafkaMessageChannelBinder.java:319)
        at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.doBindProducer(KafkaMessageChannelBinder.java:101)
        at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:155)
        at multibinder.TwoKafkaBindersApplicationTest.messagingWorks(TwoKafkaBindersApplicationTest.java:96)

**Comment by mbogoevici** [comment]
Hi @styjdt,

I've made changes to the tests to align them with latest Spring Cloud Stream - please grab latest master.

**Comment by styjdt** [comment]
Thanks, everything works.
